name: Package ComfyUI

on:
  workflow_dispatch:
    inputs:
      comfyui_branch: 
        default: master
        description: ComfyUI branch to package
      base_image:
        default: rocm7.2_ubuntu24.04_py3.12_pytorch_release_2.9.1
        description: Base image

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build ComfyUI image
        run: |
          cd ./docker
          docker build \
            -t naata/comfyui-rocm:${{ inputs.base_image }}_${{ inputs.comfyui_branch }} \
            --build-arg BASE_IMAGE=${{ inputs.base_image }} \
            --build-arg COMFYUI_VERSION=${{ inputs.comfyui_branch }}
            .

      - name: Login to Docker Container Registry
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push docker images
        run: |
          docker push naata/comfyui-rocm --all-tags
