name: Package ComfyUI
run-name: Package ComfyUI branch ${{ inputs.comfyui_branch }} with ${{ inputs.base_image }}
on:
  schedule:
     - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      comfyui_branch: 
        default: master
        description: ComfyUI branch to package
      base_image:
        type: choice        
        default: rocm7.2.1_ubuntu24.04_py3.14_pytorch_2.10.0
        options:
          - rocm7.2.1_ubuntu24.04_py3.14_pytorch_2.10.0
          - rocm7.2.1_ubuntu24.04_py3.12_pytorch_release_2.9.1
        description: Base image for ROCM/PyTorch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Resolve base image
        id: resolve-base-image
        run: |
          base_image=${{ inputs.base_image }}
          if [[ ${{ github.event_name }} == 'schedule' ]]; then
            base_image="rocm7.2.1_ubuntu24.04_py3.14_pytorch_2.10.0"
          fi
          echo "base_image=${base_image}" >> "$GITHUB_OUTPUT"

      - name: Resolve latest ComfyUI tag
        id: resolve-latest-tag
        run: |
          last_tag=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/comfy-org/ComfyUI '*.*.*' | tail --lines=1 | cut --delimiter='/' --fields=3)
          tag=${{ steps.resolve-base-image.outputs.base_image }}_comfyui_${last_tag}
          image_exists=$(docker manifest inspect naata/comfyui-rocm:${tag} > /dev/null; echo $?)
          if [[ "$image_exists" == "1" ]]; then
            echo "build_tagged=true" >> "$GITHUB_OUTPUT"
          fi

          echo "comfyui_tag=${last_tag}" >> "$GITHUB_OUTPUT"
          exit 0

      - uses: ./actions/package
        name: Nightly - Package ComfyUI latest tag
        if: ${{ github.event_name == 'schedule' && steps.resolve-latest-tag.outputs.build_tagged == 'yes' }}
        with:
          base_image: ${{ steps.resolve-base-image.outputs.base_image }}
          comfyui_branch: ${{ steps.resolve-latest-tag.outputs.comfyui_tag }}
          docker-username: ${{ secrets.DOCKER_USER }}
          docker-password: ${{ secrets.DOCKER_TOKEN }}
          repository: naata/comfyui-rocm
          image_tag: ${{ steps.resolve-base-image.outputs.base_image }}_comfyui_${{ steps.resolve-latest-tag.outputs.comfyui_tag }}

      - uses: ./actions/package
        name: Nightly - Package ComfyUI latest tag
        if: ${{ github.event_name == 'schedule' && steps.resolve-latest-tag.outputs.build_tagged == 'yes' }}
        with:
          base_image: ${{ steps.resolve-base-image.outputs.base_image }}
          comfyui_branch: ${{ steps.resolve-latest-tag.outputs.comfyui_tag }}
          docker-username: ${{ secrets.DOCKER_USER }}
          docker-password: ${{ secrets.DOCKER_TOKEN }}
          repository: naata/comfyui-rocm
          image_tag: ${{ steps.resolve-base-image.outputs.base_image }}_comfyui_latest-tag

      - uses: ./actions/package
        name: Package ComfyUI
        if: github.event_name == 'workflow_dispatch'
        with:
          base_image: ${{ steps.resolve-base-image.outputs.base_image }}
          comfyui_branch: ${{ inputs.comfyui_branch }}
          docker-username: ${{ secrets.DOCKER_USER }}
          docker-password: ${{ secrets.DOCKER_TOKEN }}
          repository: naata/comfyui-rocm
          image_tag: ${{ steps.resolve-base-image.outputs.base_image }}_comfyui_${{ inputs.comfyui_branch }}

      - uses: ./actions/package
        name: Nightly - Package ComfyUI master
        if: github.event_name == 'schedule'
        with:
          base_image: ${{ steps.resolve-base-image.outputs.base_image }}
          comfyui_branch: master
          docker-username: ${{ secrets.DOCKER_USER }}
          docker-password: ${{ secrets.DOCKER_TOKEN }}
          repository: naata/comfyui-rocm
          image_tag: ${{ steps.resolve-base-image.outputs.base_image }}_comfyui_master
