name: Package ComfyUI
run-name: Package ComfyUI branch ${{ inputs.comfyui_branch }} with ${{ inputs.base_image }}
on:
  schedule:
     - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      comfyui_branch: 
        default: master
        description: ComfyUI branch to package
      base_image:
        type: choice        
        default: rocm7.14.1_ubuntu26.04_py3.14_pytorch_release_2.11.0
        options:
          - rocm7.14.1_ubuntu26.04_py3.14_pytorch_release_2.11.0
          - rocm7.2.1_ubuntu24.04_py3.14_pytorch_2.10.0 
        description: Base image for ROCM/PyTorch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Resolve base image
        id: resolve-base-image
        run: |
          base_image=${{ inputs.base_image }}
          if [[ ${{ github.event_name }} == 'schedule' ]]; then
            base_image="rocm7.14.1_ubuntu26.04_py3.14_pytorch_release_2.12.0"
          fi
          echo "base_image=${base_image}" >> "$GITHUB_OUTPUT"

      - name: Resolve latest ComfyUI tag
        id: resolve-latest-tag
        run: |
          prefix=${{ steps.resolve-base-image.outputs.base_image }}_comfyui
          last_tag=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/comfy-org/ComfyUI '*.*.*' | tail --lines=1 | cut --delimiter='/' --fields=3)
          version_tag=${prefix}_${last_tag}
          image_exists=$(docker manifest inspect naata/comfyui-rocm:${version_tag} 1> /dev/null 2> /dev/null; echo $?)

          echo "image_exists=${image_exists}" >> "$GITHUB_OUTPUT"
          echo "comfyui_tag=${last_tag}" >> "$GITHUB_OUTPUT"
          echo "version_tag=${version_tag}" >> "$GITHUB_OUTPUT"
          echo "latest_tag=${prefix}_latest-tag" >> "$GITHUB_OUTPUT"
          echo "any_tag=${prefix}_${{ inputs.comfyui_branch }}" >> "$GITHUB_OUTPUT"


      - uses: ./actions/package
        name: Package ComfyUI - ${{ steps.resolve-latest-tag.outputs.version_tag }}
        if: ${{ steps.resolve-latest-tag.outputs.image_exists == '1' }}
        with:
          base_image: ${{ steps.resolve-base-image.outputs.base_image }}
          comfyui_branch: ${{ steps.resolve-latest-tag.outputs.comfyui_tag }}
          docker-username: ${{ secrets.DOCKER_USER }}
          docker-password: ${{ secrets.DOCKER_TOKEN }}
          repository: naata/comfyui-rocm
          image_tag: ${{ steps.resolve-latest-tag.outputs.version_tag }}

      - uses: ./actions/package
        name: Package ComfyUI - ${{ steps.resolve-latest-tag.outputs.latest_tag }}
        if: ${{ steps.resolve-latest-tag.outputs.image_exists == '1' }}
        with:
          base_image: ${{ steps.resolve-base-image.outputs.base_image }}
          comfyui_branch: ${{ steps.resolve-latest-tag.outputs.comfyui_tag }}
          docker-username: ${{ secrets.DOCKER_USER }}
          docker-password: ${{ secrets.DOCKER_TOKEN }}
          repository: naata/comfyui-rocm
          image_tag: ${{ steps.resolve-latest-tag.outputs.latest_tag }}

      - uses: ./actions/package
        name: Package ComfyUI - ${{ steps.resolve-latest-tag.outputs.any_tag }}
        if: github.event_name == 'workflow_dispatch'
        with:
          base_image: ${{ steps.resolve-base-image.outputs.base_image }}
          comfyui_branch: ${{ inputs.comfyui_branch }}
          docker-username: ${{ secrets.DOCKER_USER }}
          docker-password: ${{ secrets.DOCKER_TOKEN }}
          repository: naata/comfyui-rocm
          image_tag: ${{ steps.resolve-latest-tag.outputs.any_tag }}
